CREATE TABLE visitors (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  ip VARCHAR2(50) NOT NULL,
  user_agent VARCHAR2(255) NOT NULL,
  visit_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);


INSERT INTO visitors (ip, user_agent) VALUES ('asd', 'User Á¤º¸');




select * from visitors;

